### PR TITLE
Add enableReinitialize option

### LINKED ISSUE #2: Add enableReinitialize option
### Request:

I think it would be valuable to be able to change `defaultValue` after the initial render. This would be particularly useful when the default value is being provided asynchronously (I ran into this immediately when using `react-stepper-primitive` for the first time).

### Current behavior:

`react-stepper-primitive` honors the first `defaultValue` provided but does not update the value if the `defaultValue` prop changes.

### Reproduction:

~https://codesandbox.io/s/rr3z98y0qo~

### Proposed behavior:

Behind a non-default flag (e.g. `enableReinitialize`), `react-stepper-primitive` should honor the first `defaultValue` provided and update the current value if the `defaultValue` prop changes and the current value is still the original `defaultValue` (that is, it should not reset the current value to the new default if `defaultValue` prop changes but the user has already changed the current value manually as I think that would be pretty jarring and unexpected).

See [Formik #181](https://github.com/jaredpalmer/formik/pull/181) for prior art. Thoughts?

### PR DESCRIPTION
**Pull request by wKovacs64**
### Results:

~https://codesandbox.io/s/wk91jx6597~

Closes #2.

### CODE REVIEW

**Comment by wKovacs64** [comment]
The CI build is failing because `babel-eslint@8` [has an issue](https://github.com/babel/babel-eslint/issues/487) with class properties, by the way. [Tests pass using `babel-eslint@7`](https://travis-ci.org/wKovacs64/react-stepper-primitive/builds/325187989).

**Comment by ajoslin** [comment]
LGTM, thanks @wKovacs64. Could you update the babel-eslint dep too then I'll merge?

**Comment by wKovacs64** [comment]
Reverted `babel-eslint` to `7.2.3` to fix the build.

**Comment by ajoslin** [comment]
Released v1.1.0. Thanks again.

**Comment by wKovacs64** [comment]
Thanks!

**Pull request merged**
